### ISSUE TITLE
Produce new primer videos

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#429] opened 2015-11-12 23:27 UTC
The following primers have been recorded and edited by @schasteen and are ready for production. 

Please produce them with the bumpers and send to @schasteen for review. 

- [x] Build an Atom (please reduce fan noise)
- [x] Molecule Shapes (reduce fan noise and replace sentence)
- [x] Molecule Shapes Basics (reduce fan noise and replace sentence)
- [x] Beer's Law
- [x] Concentration
- [x] Molarity
- [x] Balloons and Static Electricity (may already be done)

@oliver-phet said you could get to this in the next week or two since budgets are finished. Please let us know if this does not seem possible.

**Comment by arnabp** [comment] 2015-11-13 02:15
School has been extremely busy lately, so I'm not always able to come in as often as I want, but I can definitely prioritize this over the next few weeks.

**Comment by arnabp** [comment] 2015-11-20 18:43
I took a look at the ones you listed. The fan noise seems VERY minimal. I can take it out, but I just wanted to make sure that it was these sims that you were referring to, as opposed to other videos I might be missing that may have more severe background noise.

Where/How do I find the sentence I'm supposed to change in molecule shapes and molecule shapes basics?

**Comment by schasteen** [comment] 2015-11-20 19:21
Arnab,

I'll listen again to the fan noise, perhaps it's not as bad as I thought.  I'm on a call until 1 and then will look.
For the sentence, are you unable to locate it?  I would just have to listen to the whole primer to locate it.  Have you done so and can't find it?

Stephanie

On Nov 20, 2015, at 11:43 AM, arnabp <notifications@github.com<mailto:notifications@github.com>> wrote:


I took a look at the ones you listed. The fan noise seems VERY minimal. I can take it out, but I just wanted to make sure that it was these sims that you were referring to, as opposed to other videos I might be missing that may have more severe background noise.

Where/How do I find the sentence I'm supposed to change in molecule shapes and molecule shapes basics?

**Comment by arnabp** [comment] 2015-11-20 19:54
I listened to both and nothing really seemed out of place. Am I supposed to know it when I hear it?

**Comment by schasteen** [comment] 2015-11-20 19:59
It wouldn't be out of place.  It's a sentence which is incorrect/misleading in its' content and we are replacing it with the corrected sentence.

As indicated in the notes,
We want to replace "This function of the simulation allows students to discover that double and triple bonds have the same influence on molecule shape as a single bond."

We are replacing that sentence with the one that Amanda re-recorded.
Were you not able to locate the sentence, "This function of the simulation allows students to discover that double and triple bonds have the same influence on molecule shape as a single bond." ?

On Nov 20, 2015, at 12:54 PM, arnabp <notifications@github.com<mailto:notifications@github.com>> wrote:


I listened to both and nothing really seemed out of place. Am I supposed to know it when I hear it?

**Comment by arnabp** [comment] 2015-11-20 20:08
Ah, it appears I forgot about the notes on the spreadsheet of the sims. I've found what was being referenced, shouldn't be a problem now.

**Comment by schasteen** [comment] 2015-11-20 20:16
I updated the notes in the List of Sim Primers to include the exact timecode, and some specific notes on fan noise.
https://docs.google.com/spreadsheets/d/1zlelf5q9txcK86WLkdCeYKoCtlxlhGDNJlT1fPmkSSk/edit#gid=0

On Nov 20, 2015, at 1:08 PM, arnabp <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, it appears I forgot about the notes on the spreadsheet of the sims. I've found what was being referenced, shouldn't be a problem now.

**Comment by oliver-phet** [comment] 2015-12-03 19:22
@arnabp Can you give a status update on this task?

**Comment by schasteen** [comment] 2015-12-29 00:27
I'm not sure how to edit the original task, but there are now several more primers to be produced.  All are in the list of sims, at https://docs.google.com/spreadsheets/d/1zlelf5q9txcK86WLkdCeYKoCtlxlhGDNJlT1fPmkSSk/edit#gid=0
Make sure to look at the Notes, as they sometimes have some instructions.

Primers to be produced:
Beer's Law
Build an Atom
Concentration
Molarity
Molecule Shapes
Molecule Shapes Basics
Balloons and Static Electricity (may already be done)

There is a separate task for the items to be reproduced.

You will still get to these during break?

**Comment by arnabp** [comment] 2015-12-29 21:18
Yes, I'll be back in the office every day now, I can definitely get these done.

**Comment by arnabp** [comment] 2016-01-04 22:15
On Molarity I can add the concentration simulation is a pop up as requested, but how do you want me to do this? Should it slide in for a few seconds every time? Or do you just want to see it once?

There's also another issue with this. Vimeo doesn't support adding annotations to their videos, so there are three ways we can approach this. We can give the direct link to the simulation (which would be clunky), we can ask them to go to the Concentration simulation without any direct link (which could potentially be confusing), or we can ask them to click on the link below the video and put in a URL in the subsection through HTML in the phet website (which might not look very clean).

**Comment by schasteen** [comment] 2016-01-04 22:18
I think it should just slide in once.   If you create something for one primer, we can look and see what we think.

I didn’t expect this to be any annotation in Vimeo necessarily, just something on-screen to show that this is a separate sim.   I hadn’t expected to put in a link.  But others can indicate if they disagree.



On Jan 4, 2016, at 3:15 PM, arnabp <notifications@github.com<mailto:notifications@github.com>> wrote:


On Molarity I can add the concentration simulation is a pop up as requested, but how do you want me to do this? Should it slide in for a few seconds every time? Or do you just want to see it once?

There's also another issue with this. Vimeo doesn't support adding annotations to their videos, so there are three ways we can approach this. We can give the direct link to the simulation (which would be clunky), we can ask them to go to the Concentration simulation without any direct link (which could potentially be confusing), or we can ask them to click on the link below the video and put in a URL in the subsection through HTML in the phet website (which might not look very clean).

**Comment by arnabp** [comment] 2016-01-04 22:43
I created two versions of the Molarity primer, v3 has the slide in, it's a bit rough (I'd probably adjust the little bubble beneath the primer to be a more fitting font and color).

**Comment by schasteen** [comment] 2016-01-07 18:04
I like the slide-in, especially with the little bit of action that you added (though I hadn't expected to get that fancy with it).  The fancier we are, the more trouble it is to do this every time another sim is mentioned, but it's most likely to happen with sims that are in a set, like these chemistry concentration simulations.  @amyh-phet, can you take a look and see if you like it?  If we do like this, Arnab, we'll want you to do this for the other chemistry primers where another sim is mentioned.  Amy, maybe you can give us a list of the primers you've made that mention other sims?

**Comment by schasteen** [comment] 2016-01-07 18:24
It wasn't clear if the new primers were ready for me to review, so I did review them all, and put comments in the new Column G in the list of sims needing primers about any changes needing to be made. Some weren't done and one had some problems but otherwise looked good.  Thanks for all this, Arnab.  Note that this task is higher priority than the "reproducing primers" task, so prioritize this.

**Comment by amyh-phet** [comment] 2016-01-07 21:52
@arnabp and @schasteen   I think the Molarity primer looks good with the slide-in.   I agree that we don't need to show actions in the slide-in if it makes production more complicated (although it was really fun to see the sim in action).   

Primers that mention other sims:
Concentration - mentions Beer's Law lab
Beer's Law - mentions looking at the Concentration sim page for the teacher tips

**Comment by arnabp** [comment] 2016-01-11 19:47
Adding in the slide in of the sim in action really isn't much more difficult than a screenshot (just adds a bit of rendering time). I can go ahead and look at concentration and beer's law and add those in.

I've adjusted the audio on Molecule Shapes and Molecule Shapes Basics. Background noise should be mostly gone, however, adding in the extra bit of audio is tricky. Audio consistency is REALLY hard without something like a soundbooth when recorded at a different time, so the clip sounds really off in the middle of the original recording. I tried to manipulate to make it sound more similar, but nothing really helped very much. I've updated both so you can listen and see what you think, but if it doesn't sound good the best option will probably be to simply re-record all the audio again.

**Comment by schasteen** [comment] 2016-01-11 19:54
I’ll listen to Molecule Shapes and see if we should re-record.

For the slide-in of sims, please take a quick listen through the other primers, since I think there are times when other sims are mentioned other than just Beers Law and Concentration.  Maybe you can listen on 2X speed, or scan through the scripts (which you should have), just to make sure we get them all.

Please also document the process you use to create the slide-in, in the Producer Guidelines, so that someone else could follow the process.

Thanks!

**Comment by amyh-phet** [comment] 2016-01-11 19:59
I just listened to Molecule Shapes and the inserted sentence is definitely notable.  Stephanie, let me know what you think.  I can record again if needed, but won't get to it until next week as I'm at a conference T-F this week.

**Comment by schasteen** [comment] 2016-01-11 23:51
I’m surprised the inserted sentence sounds that different — it actually sounds like it was recorded with a different mic and maybe at a different distance (further) from the mic.   Amy, do you know if you used the same setup in this recording?   If not, maybe we could better replicate the original recording.  I don’t mind if it sounds off, but this is quite off. 

 Arnab, it sounds like you tried modifying several things; boosting the bass and decreasing treble didn’t help?   That seems to be the thing that’s throwing it off the most.  

That said, I know from experience how hard it is to get inserted audio to sound good — I just didn’t expect it to sound this off, and so I’m wondering if there is anything that can be done in recording or post production that would be easier than re-recording the whole thing.

Amy, we could also use the original audio; we changed it for a reason, because I felt it was not clear, but if it is very time consuming to re-record audio, we could use the original audio.  Or, if you think it’s pretty straightforward to re-record the audio, we could do that, and we’ll know it’ll work.

**Comment by amyh-phet** [comment] 2016-01-11 23:57
I did use  the same mic, but given our recording set up, it is extremely hard to make sure I'm the same distance from the mic when recording at different times.  I don't think re-recording would be that time consuming.  I can work on this next Tuesday.

**Comment by arnabp** [comment] 2016-01-12 22:51
Yes, I'm afraid changing things didn't help too much. The problem was that the re-recorded clip sounded a little worse, and while I can make good audio sound close to bad audio, it's harder to make bad audio sound good. 

Fraction Matcher screenshot resolution should be fixed and ESPB should be fixed.

I'll spend the rest of the week looking through sims for slide in references and adding those in, along with making the little blurb in the producers guidelines.

**Comment by amyh-phet** [comment] 2016-01-13 19:37
@arnabp  I'll do my best to get you new recordings of Molecule Shapes: Basics and Molecule Shapes by next Wednesday.

**Comment by schasteen** [comment] 2016-01-19 18:43
Arnab, while you are waiting for Amy to record, here are the outstanding tasks that we identified:
- Identify primers mentioning other sims, and insert screenshot accordingly
- BAA had an issue in the primer (see List of Sims Needing Primers)

**Comment by arnabp** [comment] 2016-02-12 22:29
I've put in the recordings, they sound great, and the new video files are in their respective folders. Next week I'll start combing through the simulations looking for areas I can add slide ins.

**Comment by arnabp** [comment] 2016-02-17 23:08
Outside of Molarity, I found two other simulations that reference other sims: Concentration and Beer's Law. I'll add in their slide ins this week, let me know if you think there's any other sim where I missed a simulation reference.

**Comment by amyh-phet** [comment] 2016-02-18 18:19
@arnabp  These should be the only other primers that reference other sims.  Thanks for tracking this down and putting the slide-ins into the primers.

**Comment by arnabp** [comment] 2016-02-22 22:51
I've put in the slide ins for Concentration and Beer's Law, I've also updated the producer guidelines to explain the process. That appears to be everything I think? Let me know if there's anything else missing that I should do.

**Comment by schasteen** [comment] 2016-02-23 19:25
Concentration and Beer's Law are OK.  However, I note that the Camtasia date in the file name doesn't match the mp4 date.  For consistency, they should, so we know which Camtasia was used to produce the mp4.  E.g., instead of Concentration_v4_v15_12302015 it should be Concentration_v4_v15_02172016.  Could you update these Camtasia file names for our archives?

Really nice documentation on the slide-in process, thank you.

Molecule Shapes:  I'm assuming that this file is erroneously called FractionMatcher_V2_V15_02122016.  I reviewed this, and it looks fine.
Molecule Shapes Basics:  I reviewed molecule_shapes_basics_v1_v15_02122016 and it looks fine, but I noticed the date on the file is one day earlier than the matching Camtasia.  

So, these are all OK to upload to Vimeo.   Let us know when that's done so we can get started on subtitling.

**Comment by arnabp** [comment] 2016-02-24 23:15
I've fixed all incorrect file names and added the note to Balloons. When I reupload the sims that were updated to V15, should I simply replace the existing Vimeo file for those or create a new video altogether on vimeo? Also, what is PBU2? I couldn't find it anywhere on the producer guidelines.

**Comment by schasteen** [comment] 2016-02-25 00:25
Yes, replace the existing Vimeo file for the updated sim primers.  PhET Backup 2 = PBU2.  The producer guidelines that refer to it are:
In PhET Backup 2, create an archival copy of all information in the Draft Primer and Final Primer folder for that sim (PhET Backup 2 / SEI Media / PhET Teacher Primers) including a Word copy of the outline and reviewer comments.
Don’t delete anything from Google Drive; I’ll check the archives and make changes to Google Drive once I see it’s all archived OK.

**Comment by schasteen** [comment] 2016-03-08 18:40
@arnabp, please provide an update on status.

**Comment by arnabp** [comment] 2016-03-09 03:41
Sorry, I was sick most of last week. I've started uploading the primer data to PBU2, and I'll be updating and adding the new vimeos later this week.

**Comment by arnabp** [comment] 2016-03-11 23:13
I have archived all the sim primer files to PBU2 and uploaded/updated all sim primer videos on Vimeo. Let me know if everything looks okay!

**Comment by schasteen** [comment] 2016-03-15 22:57
This looks good so far, except that PBU2 contains .gdoc files of the primer outline/scripts.  Those need to be exported as Word documents.  I know it's a pain, but those scripts are important documentation.  You can do it for the outlines only and not the review.

Also, it looks like the "reproducer primer videos" issue has not been addressed yet, correct?  Once that's done and all is archived in Vimeo, I will carefully review everything.
Here is the reproduce primer video issue:  https://github.com/phetsims/tasks/issues/430

**Comment by ariel-phet** [comment] 2016-03-15 23:07
@schasteen can you comment one why these need to be exported as word documents? They can be viewed as google docs from the archived file correct?

**Comment by schasteen** [comment] 2016-03-16 15:37
Ariel — exporting the script as Word was the guideline that Yuen-Ying and I developed when we documented the Primer process.  The archive of all primers is on Phet Backup 2, which is an external drive, not on Google.  The thinking was that we wanted a complete, readable archive right there on PBU2, so that if, in 5 years, we needed to re-record the primer, we would have an archive of all pieces of the primer (video, Camtasia, Word) that has longevity.  If Google Docs changes their system, for example, the .gdoc file may no longer be readable.  We have also had weird issues (Arnab knows more than I do about this though) in trying to take a .gdoc file out of Google Drive and then putting it back in to open it.  Sometimes that doesn’t work.  Archiving as a Word file seemed the safest way to make sure we had a single folder with everything we’d need to reproduce the primer.  It seemed a simple step to safeguard that work.  Of course, we could always transcribe the original primer, but if we needed to reproduce a bunch of primers for some reason, that would be onerous.  So, the cost seemed small for that added benefit.

That was our rationale.  If it seems too troublesome, let me know if you want me to change the Guidelines in our documentation.

On Mar 15, 2016, at 5:07 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@schasteen<https://github.com/schasteen> can you comment one why these need to be exported as word documents? They can be viewed as google docs from the archived file correct?

**Comment by oliver-phet** [comment] 2016-03-16 15:51
If you are going to be downloading multiple scripts to word docs, it would be most efficient to use Google takeout.

**Comment by ariel-phet** [comment] 2016-03-16 15:52
@schasteen thanks for the info

It might be good to note that the plan is to eventually migrate all of our backups to google drive (since the university gives us unlimited storage if we use colorado.edu google accounts). So in the nearish future all data on PBU, and PBU2 are going to be moved to a google drive account (something like phet-storage). You might not have been aware of that plan, but if we are going to be using google drive (eventually for our storage) it might be unnecessary to convert to word docs. I would also note, that if a file has remained in drive, we can open even the oldest google docs in the project without issue.

Your call, I would not call it "troublesome", but it might be unnecessary considering the future plans for backup.

**Comment by arnabp** [comment] 2016-03-16 21:48
Converting to word may be more solid and reliable, but since the backups are all going to google drive anyway it may not matter. Let me know what you want me to go with.

**Comment by oliver-phet** [comment] 2016-03-16 22:08
Since we are going to be moving PBU to PhET-storage, I don't think we should worry about individually exporting these as Word docs at the moment. We can always do a google takeout of the files if there is an immediate need.

**Comment by schasteen** [comment] 2016-03-16 22:14
OK, given that PBU2 will move to Google, we’ll go with archiving google docs only.

**Closed** 2016-03-24 19:51 UTC
Labels: design:teaching-resources, priority:2-high
