### ISSUE TITLE
Test color-vision/1.2.4-phetio

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#837] opened 2017-05-08 16:30 UTC
For https://github.com/phetsims/color-vision/issues/115 we created a maintenance release for Color Vision PhET-iO.  Before we can share it back to the client that reported the problem, we need to make sure the DT caps are working properly and nothing else has been disrupted.  To test the dt caps, launch both:
https://phet-io.colorado.edu/sims/color-vision/1.2.3-phetio/wrappers/index/
https://phet-io.colorado.edu/sims/color-vision/1.2.4-phetio/wrappers/index/

in the browser, then open a different tab and wait 30 minutes.  Then visit 1.2.3 and 1.2.4 and see which one(s) lag/pause/crash.  Also test through the other time-dependent behavior to make sure the dt caps don't have any undesirable behavior, and make sure that nothing else was disturbed since 1.2.3.

In https://github.com/phetsims/color-vision/issues/115#issuecomment-299665655 @kathy-phet said "I agree we should figure this out as a priority." and it would be good to get the fix to BrainPOP after it is verified.  If this version checks out, the link can be shared directly without another release step.

Reassigning to @ariel-phet for prioritization and delegation.

**Comment by ariel-phet** [comment] 2017-05-09 03:15
@phet-steele marking as current top priority since a client pointed out this bug

**Comment by ariel-phet** [comment] 2017-05-10 03:04
Moving to high priority right behind #838 (perhaps @EthanWJohnson can polish this off?)

**Comment by EthanWJohnson** [comment] 2017-05-10 20:36
I had let it sit for a while before #838 went up. 1.2.3 lagged to non-responsiveness, 1.2.4 didn't slow down at all.

**Comment by phet-steele** [comment] 2017-05-23 19:28
@samreid sorry this took so long. As @EthanWJohnson said, https://github.com/phetsims/color-vision/issues/115 is not a problem in 1.2.4 and no regression was obvious.

**Closed** 2017-05-31 16:36 UTC
Labels: dev:phet-io, tasks:QA
