### ISSUE TITLE
Review phet-info/doc/phet-software-design-patterns.md

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#977] opened 2019-01-03 20:28 UTC
From https://github.com/phetsims/tasks/issues/969#issuecomment-451265925 @ariel-phet recommended that all PhET developers are aware of this doc.  @pixelzoom volunteered to take an initial look through this document.

**Comment by pixelzoom** [comment] 2019-01-03 20:32
Duplicate of https://github.com/phetsims/phet-info/issues/88.

**Closed by pixelzoom** 2019-01-03 20:32 UTC
