### ISSUE TITLE
IntelliJ IDEA 2016.1 takes too long to push

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#547] opened 2016-03-18 02:03 UTC
I reported this issue the development team today, and made a bug report to IDEA, this issue is to track the problem.  The JetBrains bug report is here: https://youtrack.jetbrains.com/issue/IDEA-153191

I'm going to use 15.0.2 until this is fixed or worked around.

**Comment by samreid** [comment] 2016-04-05 20:58
Resolved in the issue above, closing.

**Comment by samreid** [comment] 2017-01-04 00:01
@pixelzoom and I are still seeing this problem.  Reopening.

**Comment by samreid** [comment] 2017-01-04 00:22
I shared a 1-minute long video that shows the problem and the workaround:
https://drive.google.com/a/colorado.edu/file/d/0B8guh7oYpZbQNW9oVGxZT0tneG8/view?usp=sharing

**Comment by samreid** [comment] 2017-01-04 00:27
My hypothesis about how this problem occurs is:

1. after making changes in repo X, it is marked "dirty" by IDEA (and gets a "-" in the push dialog)
2. when committing changes to repo Y, then showing the push dialog, it iterates through all repos to check if they need to be pushed. Repos with "-" that do not show any commits are changed to "unchecked".  If you press "push" before it clears "-" to "unchecked", then it thinks it needs to push to X.

**Comment by samreid** [comment] 2017-01-04 00:29
Testing this:
it seems any repo with "-" or "checked" gets pushed.  If you wait long enough for it to iterate through all of them and convert "-" to "unchecked" there is no problem.  If you manually uncheck one that got converted from "-" to "unchecked" to "checked" then "unchecked", then push, then IDEA remembers and doesn't mark the repo as "-" for next push.

**Comment by samreid** [comment] 2017-01-04 00:30
If we could easily reproduce the creation of a "-", that should be reported to JetBrains.

**Comment by pixelzoom** [comment] 2017-01-04 01:15
@samreid wrote:
> If you wait long enough for it to iterate through all of them and convert "-" to "unchecked" there is no problem.

Confirmed.  In the upper-right corner of the left pane, there is a busy indicator (see screenshot below). If I wait for the busy indicator to disappear, then "there is no problem". 

![screenshot_260](https://cloud.githubusercontent.com/assets/3046552/21628906/9801cb3c-d1e0-11e6-9381-e3f0b9458936.png)

**Comment by pixelzoom** [comment] 2017-01-05 17:40
Now that I know to wait for the busy indicator to complete... The first time I need to wait awhile for it to complete.  But after that, it completes quickly.  So it seems like this is a case of "be patient the first time" and then you won't encounter the problem.  My workflow is no longer being disrupted, so unassigning myself from this issue.

**Comment by pixelzoom** [comment] 2017-01-05 17:41
Also worth noting that the "check and uncheck repos" workaround doesn't really do anything -- it's waiting for the busy indicator to complete that does the trick.

**Comment by samreid** [comment] 2017-01-05 17:41
I'm not planning to investigate further, unassigning myself for now.

**Comment by ariel-phet** [comment] 2018-03-06 02:50
Seems to be a non-issue now. Closing

**Closed by ariel-phet** 2018-03-06 02:50 UTC
Labels: tasks:developer
