### ISSUE TITLE
What do we do with the "sim suggestions" list?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#224] opened 2015-04-21 16:14 UTC
In 4/21/15 developer meeting notes, @ariel-phet asked:
> Sim suggestion doc in unfuddle, should this perhaps be triaged and relevant ones moved to github (not a high priority, but seems like they will wallow in “the ether” on unfuddle)

The general consensus at the meeting is that this should be moved to a Google doc.

**Comment by ariel-phet** [comment] 2015-04-23 22:28
duplicate of https://github.com/phetsims/tasks/issues/227, closing

**Closed by ariel-phet** 2015-04-23 22:28 UTC
