### ISSUE TITLE
Should we get rid of the `meeting:developer` label?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#1095] opened 2021-12-02 23:03 UTC
At today's developer meeting, @zepumph said it has been unwieldy to try to keep the `meeting:developer` label in sync with the project board.  @samreid reported that sometimes it is nice to be able to filter on the label or see it in a list.  Should we still have both and try to keep them in sync?  Should we just use the project board for the meeting?

**Comment by zepumph** [comment] 2021-12-02 23:27
I looked only briefly through https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects, but with the new Project Boards (Beta), it seems like we can write a custom action that would add that label when the issue is added to the project board.

**Comment by pixelzoom** [comment] 2021-12-08 20:00
+1 for deleting the label and using the Developer Meeting project board going forward. While it may be "nice to have" the label too, I don't feel like it's worth the extra effort.

**Comment by samreid** [comment] 2021-12-08 21:28
Issue searches can filter based on whether something is on a project board like `-project:phetsims/35`.  That will work for my purposes for the moment.  Will we lose any important information if we delete the meeting:developer label?  What if we want to resurrect it one day?  Should we try a phase where "we haven't deleted the meeting:developer label, but we just aren't using it at all for now", or will that be too confusing?

**Comment by mattpen** [comment] 2021-12-09 16:28
> Should we try a phase where "we haven't deleted the meeting:developer label, but we just aren't using it at all for now", or will that be too confusing?

If we delete it, we would lose history, i.e. we couldn't answer the question "which closed issues have the developer:meeting label?" However, I don't think we've been using it consistently enough to be able to answer this questions even with the label in place.

If the label stays in place I'm pretty sure I would make the mistake of using it instead of the project board.  If the label is deleted, I'll probably remember "oh yeah, I need to use the project board" when I try to add it.

IMO we should just delete it, it's easy to readd if we find that it is sorely missed.

**Comment by samreid** [comment] 2021-12-09 17:07
> IMO we should just delete it, it's easy to readd if we find that it is sorely missed.

We also discussed the case of looking at a paper trail of an issue.  What if an issue was labeled for dev meeting in March, then worked on, then the label was removed.  What happens to that paper trail if we delete the label?  Also, there is probably not a way to restore that paper trail at all.

With this proposal: try a phase where "we haven't deleted the meeting:developer label, but we just aren't using it at all for now":

* If the problem is "it takes too much time to label for dev meeting and project board and keep those in sync", that problem is solved--just mark it for the project board and ignore the label.
* If the problem is "what if a developer forgets to label it for the project board and instead marks it with the dev meeting label?"  That is solved by clicking on the "Issues labeled but not yet on the project board" link in the dev meeting.  Hopefully over time we will learn to just use the project board by default.

**Comment by zepumph** [comment] 2021-12-10 20:57
>That is solved by clicking on the "Issues labeled but not yet on the project board" link in the dev meeting. Hopefully over time we will learn to just use the project board by default.

As someone who has kept these in sync manually for the last few months, I don't think of this as a solution, I think of it as a workaround. I'm happy to do whatever we decide as a team. 

I don't foresee needing or caring about vestigial paper trails regarding dev meeting label, and I also won't get confused about using the project board if the label sticks around.

**Comment by samreid** [comment] 2021-12-10 22:45
Perhaps the reason I thought it wasn't too hard to keep these in sync is that you had already done most of the work before I looked each time.  I'm still slightly concerned about losing information with a delete.  I'm sure we could deal with it, but @mattpen brainstormed that we could rename the label instead of deleting it, to something like meeting:dev-deprecated.  Do you think that could be enough, or people would still use it?  Or if people are using autocomplete we could use a more severe name change like "deprecated: meeting:dev".

**Comment by samreid** [comment] 2021-12-16 19:06
@zepumph says a rename is OK.  Also OK deleting it.
@jbphet says let's just deprecate it for now.  The history doesn't matter that much, but that could preserve the history.
@mattpen is pretty confident that a rename will retain the history.  A delete would delete the paper trail from history.

@mattpen volunteered to rename the label, thanks!

`deprecated:meeting:developer`

**Comment by mattpen** [comment] 2021-12-16 19:47
The name change is complete.

The history appears to be working correctly:
![image](https://user-images.githubusercontent.com/11747676/146438430-5fac21f1-a7ac-40f2-94e0-874316ef6c40.png)

Closing!

**Closed by mattpen** 2021-12-16 19:47 UTC
Labels: deprecated:meeting:developer
