### ISSUE TITLE
Light editing + captions for John Travoltage demo video

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tasks#946] opened 2018-07-23 11:52 UTC
Captioned video needs to be completed and ready for uploading by end of day, Thursday July 26 in preparation for submission Friday July 27th.

@terracoda is creating a video demo of the sound and description of John Travoltage. Please check with @terracoda regarding when this video will be ready for captioning. This video will be submitted as supporting materials for an accepted conference paper due July 27th. Sorry for the short notice - we weren't aware this would be part of the preparation for publishing until last week. 

Caption Info:
- This video will include sound display (descriptions and sound effects/sonifications) and may include Taliesin's voice. 
- Captions are required, to ensure the video is as accessible as possible. The captions need to be easily readable, and not obscure any important aspects of the sim (including focus highlights). Please position the captions on top of the nav bar region without text/icons, or edit the video such that there is room below the sim to accomodate the captions. 
- Please check with @terracoda regarding specific questions on wording and indicating sounds, etc. for the captions.

Video Technical Requirements:
- Length maximum - 5 min or less
- Size - less than 50 MB
- Video requires MP4 encoding using the H.264 codec 
- 16:9 aspect ratio is strongly encouraged

@terracoda Additionally, I think a 250 word (max) description is required for this video as well. You can use content from the manuscript to piece this together, if that's helpful.

**Comment by terracoda** [comment] 2018-07-23 12:17
@emily-phet, thanks for creating this issue. I'm just about to do a test, and I agree keeping my voice part minimal is ideal (using content from manuscript.)

**Comment by emily-phet** [comment] 2018-07-23 12:41
@terracoda Sorry for being unclear - the comment at the end regarding the 250 word max was referring to a written description (e.g., alt text-like description) for the video on uploading to conference site. It turns out this is not required - so you can forget I said anything about it! The instructions are unclear, but I made it to the final submission page so I can see exactly what the required upload fields are now. For the video - it's just the video file only, no additional files/text/etc.

**Comment by terracoda** [comment] 2018-07-23 15:00
The transcript and times for editing are here:
https://docs.google.com/document/d/1vLy-TD_vUE3q6VUJRAM9Rvr0YykdTqPbptBPTO2jUJc/edit#

**Comment by ariel-phet** [comment] 2018-07-23 20:22
Sounds like @CWilson4960 will be able to help with this project in a timely manner. Assigning.

**Comment by CWilson4960** [comment] 2018-07-24 18:14
@emily-phet 
![image](https://user-images.githubusercontent.com/31217926/43157667-e9d18312-8f3a-11e8-94b0-3dbae808380c.png)
I'm using Camtasia to produce the captions and video. These are the settings I can change. I'm unsure how to get to MP4 encoding using the H.264 codec. I can export the video as a MP4 and change the setting shown above, but that's all I know. Any recommendations?

**Comment by terracoda** [comment] 2018-07-24 20:34
@CWilson4960, sorry I can't help here.

**Comment by emily-phet** [comment] 2018-07-26 15:51
@CWilson4960 not sure about your question regarding H.264 - can you clarify? What happens if you use H.264 that's undesirable?

For the file size question, I think the issue is the dimensions you have here. They need to be smaller to decrease the final file size. If you play around with exporting other dimension options, I think you'll find something that drops below the 50MB we need.

**Comment by amanda-phet** [comment] 2018-07-26 15:59
>What happens if you use H.264 that's undesirable? 

The issue is that H.264 doesn't appear to be an option in that screenshot. Do you know where to find encoding settings?

**Comment by emily-phet** [comment] 2018-07-26 16:03
After consulting with Google - I think mp4 files exported from Camtasia are h.264. So let's just assume that's the case, and that any under 50MB mp4 file from Camtasia fits the submission requirements.

**Comment by terracoda** [comment] 2018-07-27 06:04
Thanks @CWilson4960 and @emily-phet. It looks and sounds great to me.

**Comment by ariel-phet** [comment] 2018-07-31 23:09
Since deadline for this task has passed, assuming it can be closed. Closing.

**Closed by ariel-phet** 2018-07-31 23:09 UTC
