### ISSUE TITLE
Standardize labels for GitHub issues

### ISSUE THREAD

**Issue by phet-steele** [phetsims/tasks#465] opened 2016-01-07 18:56 UTC
Make all the labels across sim repos and tasks the same color and text.

**Comment by ariel-phet** [comment] 2016-01-08 15:58
@samreid has suggested that multiword labels such as "high priority" are hyphenated "high-priority" "code-review" "master-checklist" and such

some other standard labels that should be on all sim repos
"master-checklist"
"high-priority"
"medium-priority"
"low-priority"
"wishlist"
"requires-kathy"
"developer-meeting"
"phet-io"
"teaching-resources"
"accessibility"
"design"

especially for searches it is important to have these all exactly the same, so please modify any existing labels to be consistent.

@samreid @mattpen @jessegreenberg @pixelzoom @jonathanolson @jbphet please chime in if there are any other standard labels you wish to add to this list or if you want any of the "boiler plate" labels removed or changed

Here are the boiler plate ones that come with a new repo:

![labels](https://cloud.githubusercontent.com/assets/4051174/12202237/027dee90-b5e6-11e5-97df-76caaa4f5131.PNG)

**Comment by pixelzoom** [comment] 2016-01-08 16:00
Having to manage labels per repository is not scalable, and ensures that this tasks will need to be repeated. @phet-steele, you might consider making an official request to GitHub for a way to define labels that can be applied to all repos that are owned by an Organization.

**Comment by ariel-phet** [comment] 2016-01-08 16:02
@pixelzoom I will make that request. I think it may also be possible for us to write a tool to do this ourselves through the github API, it is something I might have @mattpen look into. But I want to get a standard set of labels rolling and settled on as well, so we will do the manual step for the moment.

**Comment by pixelzoom** [comment] 2016-01-08 16:03
Other PhET-standard labels:

code-review
deferred
phet-io-meeting
performance
licensing

... and `scenery` has a lot of labels that may or may not be specific to that repo.

**Comment by pixelzoom** [comment] 2016-01-08 16:09
How about adding something to the `phet-info` repo (github_labels.md?) that lists the labels defined by PhET and their associated colors.  That would save me a bit of time and guesswork, the next I need to (for example) add a "code-review" label.

**Comment by ariel-phet** [comment] 2016-01-08 16:14
@pixelzoom great suggestion

@phet-steele please choose one repo to do this "fresh" on. I think expression-exchange would be good since it is a new repo. And then reassign the issue to me, so that we can discuss colors and such as a team, then once we have the full list of labels and colors, I will create a reference doc.

**Comment by phet-steele** [comment] 2016-01-08 16:16
@ariel-phet Will do.

**Comment by ariel-phet** [comment] 2016-01-08 16:20
Feature request sent to Github.

**Comment by ariel-phet** [comment] 2016-01-08 16:39
reply from github

>Hi Ariel,

>Thanks for the very kind words, and for taking the time to submit feedback.

>Yeah, I agree it would be useful if there was a way to have organization-wide labels as you described. Adding that is on our feature request list, but it probably won't happen in the near future.

>For now, you could use the API to automatically create labels in repositories:

>https://developer.github.com/v3/

>Even better, if you pair that up with using organization-level webhooks, you could automatically create labels for any new repository created in your organization:

>https://developer.github.com/webhooks/

>Hope this helps and thanks again!

**Comment by ariel-phet** [comment] 2016-01-08 16:41
I think I will make an issue in chipper to investigate the above

**Comment by ariel-phet** [comment] 2016-01-08 16:46
Issue created here https://github.com/phetsims/chipper/issues/425

**Comment by phet-steele** [comment] 2016-01-08 17:18
@ariel-phet the website repo also has a lot of labels that seem pretty specific to it. So I'm thinking three options:
Should they not be put on the list and then deleted when the standard list is incorporated?
Should they not be put on the list and then not deleted when the standard list is incorporated?
Should  they be put on the list and therefore be in every repo? 

This question really applies to every repo with arguably repo-specific lables.

**Comment by ariel-phet** [comment] 2016-01-08 17:25
@phet-steele if custom labels already exist (such for the website repo), the standard list should merely augment this list, we should not add these to the standard list.

**Comment by samreid** [comment] 2016-01-08 18:12
Everything above looks good so far.  There is another label I often use, let me describe how it works and we can decide together how to name it and if we want to standardize it in our labels.

Let's say I'm working on Moving Man and the sim team + QA team have identified 4 issues that require work.  I fix the first issue, but I don't want to close it until it has been verified by the person that reported it.  I don't want to reassign it to the person that reported it until a new dev version has been posted.  And I (often) don't want to publish a new dev version until I have addressed the 3 other issues as well.

How have other developers coped with the preceding situation?  Would a label help?

**Comment by jonathanolson** [comment] 2016-01-08 18:16
@samreid, I had a "fixed-pending-testing" label for molecule-shapes for this exact reason. https://github.com/phetsims/molecule-shapes/labels/fixed-pending-testing.

@ariel-phet, list of issues looks perfect.

Setting a script up that uses the GitHub API sounds like the best path.

**Comment by samreid** [comment] 2016-01-08 18:24
@jonathanolson I think I used `ready-for-testing`, but I like `fixed-pending-testing` as a standardized-cross-repo label.

**Comment by ariel-phet** [comment] 2016-01-08 18:26
@phet-steele I believe you also had some thoughts...was "multitouch" one of them?

**Comment by phet-steele** [comment] 2016-01-08 18:32
@ariel-phet yea, it's already on my list

**Comment by ariel-phet** [comment] 2016-01-08 18:34
@phet-steele cool, please add any on your list to the comment above

**Comment by phet-steele** [comment] 2016-01-08 18:43
Here's the list so far. The first seven are the default ones (they can always be deleted thought). Should summer-2015-redeploy be added?

bug
duplicate
enhancement
help-wanted
invalid
question
wontfix

-------------------------------
master-checklist
high-priority
medium-priority
low-priority
wishlist
requires-kathy
developer
developer-meeting
phet-io
phet-io-meeting
teaching-resources
accessibility
design
design-meeting
code-review
deferred
performance
licensing
multi-touch
quality-assurance
when-time-allows
misc
translation
graphic-arts
artwork
fixed-pending-testing

**Comment by ariel-phet** [comment] 2016-01-08 18:51
hey @phet-steele I made a few edits

removed "developer" "graphic-arts" (these are very tasks repo specific) and changed "quality assurance to "QA" (faster to type)

summer-2015-redeploy does not need to be added

**Comment by pixelzoom** [comment] 2016-01-08 18:56
Here's how I handle what @samreid described in https://github.com/phetsims/tasks/issues/465#issuecomment-170078050...

I don't use labels to address this, and I close issues as I address them.   I track issues that need to be verified by associating them with their RC task. When an issue is created related to an RC test task, I put "Related to RC test phetsims/tasks#XX" as a comment in the issue (where XX is the issue number in the tasks repo).  That ensures that the issue will appear in the RC task.  When the RC test is done, I review the list of issues and provide instructions on which ones need to be verified.

For example, in "RC test: Graphing Lines 1.1.0-rc.1" (https://github.com/phetsims/tasks/issues/374), you can see the issues that were created for that RC test:

![screenshot_118](https://cloud.githubusercontent.com/assets/3046552/12206480/6c1e5c64-b5fe-11e5-9065-69137442e19b.png)

For the next RC test ("RC test: Graphing Lines 1.1.0-rc.1", https://github.com/phetsims/tasks/issues/445), I reviewed those issue, then provided the following QA instructions:

![screenshot_119](https://cloud.githubusercontent.com/assets/3046552/12206510/a34a08c8-b5fe-11e5-896f-3b9280c41e2b.png)

**Comment by pixelzoom** [comment] 2016-01-08 18:59
@ariel-phet Something that would streamline the process described in https://github.com/phetsims/tasks/issues/465#issuecomment-170091387 is if the testers would handle tagging issues with their associated RC task.  When they create an issue related to an RC test, put ""Related to RC test phetsims/tasks#XX" in the comments for the issue.  Not a big deal if they don't do this, and perhaps only relevant if other developers thing it's useful.  But it's how I keep track of what needs to be verified.

**Comment by jessegreenberg** [comment] 2016-01-08 19:45
I prefer to keep issues open until after they have been verified as fixed through further testing.  A standard label like ```fixed-pending-testing``` would help identify the status of these issues.

Referencing the RC task in the issue is also helpful for documenting and identifying changes and fixes resulting from RC testing.

I think both label and reference are helpful in documenting issue status.

**Comment by jessegreenberg** [comment] 2016-01-08 19:46
I would prefer ```a11y``` instead of ```accessibility```.  ```a11y``` is shorter to type, matches conventions of the accessibility community, and is in sync with our code documentation style.

I also prefer ```i18n``` instead of ```translation``` for similar reasons.  Changing the list, but if others disagree, they can be changed back.

**Comment by samreid** [comment] 2016-01-08 20:22
> I prefer to keep issues open until after they have been verified as fixed through further testing.

Yes, that's how I feel as well. I like the symmetry of having the same person that opened the issue be the one to close it.

**Comment by samreid** [comment] 2016-01-08 20:28
Are any of these redundant?

when-time-allows
deferred
low-priority
wishlist

I'm not sure of everyone's connotations attached to these phrases, or if these combinations would ever be used in combination.

**Comment by ariel-phet** [comment] 2016-01-09 02:17
@samreid I suppose "when-time-allows" could be nixed in favor of simply "low-priority"

"wishlist" is truly that for me - items we have thought of that would be nice one day, but we know there is no priority for

"deferred" seems like - he we should do this, but we need to punt for the moment due to other constraints.

I will go ahead and remove "when-time-allows" from the list above.

**Comment by samreid** [comment] 2016-01-09 03:12
@ariel-phet thanks for clarifying.

**Comment by phet-steele** [comment] 2016-01-11 20:57
added top priority

**Comment by pixelzoom** [comment] 2016-01-11 21:16
Surely you mean top-priority :)

**Comment by phet-steele** [comment] 2016-01-11 21:17
haha yes, that's how I added it in the list above.

**Comment by phet-steele** [comment] 2016-01-11 21:44
@ariel-phet I added all these to expression exchange so I could mess with the colors, check it out! Tell me if you change any colors, I'm keeping track of hex codes.

**Comment by ariel-phet** [comment] 2016-01-11 23:11
@phet-steele thanks...I think we will discuss at dev meeting

**Comment by ariel-phet** [comment] 2016-01-20 16:45
@phet-steele I also realized we should have a "status-meeting" label, adding that to the list

**Comment by ariel-phet** [comment] 2016-01-20 17:08
Began a table to document (which we can eventually use for a json file) here https://github.com/phetsims/phet-info/blob/e107784c98c62781bacb8905391f5f3eb17e6ce0/issue-info/labels.md

**Comment by mattpen** [comment] 2016-01-26 18:03
As soon as this table is complete, I can write a script to standardize all the repos.  It's currently missing the hex-codes for the colors.

**Comment by pixelzoom** [comment] 2016-02-01 20:37
I've seen several references (such as http://programmers.stackexchange.com/questions/129714/how-to-manage-github-issues-for-priority-etc) that recommend organizing labels into "groups", as a way to add some structure to GitHub's free-for-all label feature. Labels are grouped by using the general form `<label-group>:<label-name>`.  Labels within a group are mutually exclusive.

For example:

"type" group:
• type:bug
• type:enhancement
• type:question
• type:task

"priority" group:
• priority:low
• priority:medium
• priority:high
• priority:deferred

"status" group (to describe where an issue is in the workflow):
• status:in-progress
• status:awaiting-verification
(not sure which others would be appropriate for PhET's workflow)

This makes a lot of sense to me, but might be more complexity than PhET wants.

**Comment by ariel-phet** [comment] 2016-02-01 20:51
And don't forget the "meeting" group: :smiling_imp:

**Comment by ariel-phet** [comment] 2016-02-02 18:35
I am liking @pixelzoom suggestion in https://github.com/phetsims/tasks/issues/465#issuecomment-178176176 I am going to play with this in expression exchange as I work on the color schem

**Comment by ariel-phet** [comment] 2016-02-03 02:11
example of colors and proposed labels here using groups
https://github.com/phetsims/expression-exchange/labels?sort=name-asc

**Comment by samreid** [comment] 2016-02-03 02:19
This label may be a typo "multitouch0000FF" ?

**Comment by ariel-phet** [comment] 2016-02-03 02:20
How apropos that the multitouch label got fat fingered...fixed, thanks @samreid

**Comment by samreid** [comment] 2016-02-03 02:20
The alphabetical grouping is an unexpectedly nice feature here, I like it.

**Comment by ariel-phet** [comment] 2016-02-03 02:26
One break I decided to try from the general scheme was priority1, priority2, etc for that group name. I found when scanning the labels when creating an issue it was nice to have these in a clear hierarchy.

**Comment by ariel-phet** [comment] 2016-02-03 02:32
and I agree @samreid - the aphabetical grouping seems very efficient for this large set of labels and seem good scalability - thanks for the suggestion @pixelzoom !

**Comment by mattpen** [comment] 2016-02-03 03:55
I think these look great.  This will really help with workflow.  Are the labels in this repo finalized?  I can just use this as the model instead of the table above. I can propagate the labels throughout the rest of the organization whenever they are ready.

**Comment by samreid** [comment] 2016-02-03 03:57
> I can propagate the labels throughout the rest of the organization whenever they are ready.

Is there a migration path, so that things currently marked with "high-priority" would get mapped to the new name?  I've been out of the loop on this conversation.

**Comment by ariel-phet** [comment] 2016-02-03 04:38
@mattpen lets wait until we discuss a bit more at developer meeting. Once everything is settled I want to actually document it in the phet-info file as well as couple of examples of useful searches with labels.

**Comment by mattpen** [comment] 2016-02-03 05:17
> Is there a migration path, so that things currently marked with "high-priority" would get mapped to the new name? I've been out of the loop on this conversation.

My 2¢. Backwards compatibility with the existing labels would make automating this project significantly more complex.  For example, it would be difficult to know if a repo is using "high-priority" vs "high priority" (no hyphen) as any user can define a new label.  The website repo I know has at least one misspelled label -- "HMTL5 Sim Translation".  This would involve a lot of manual checking.

**Comment by mattpen** [comment] 2016-02-03 06:23
Discussed with @ariel-phet in a Skype call.  One possible solution is pushing the new labels but not removing the old labels, then having @phet-steele or another QA person manually adjust any duplicate labels in the repos with a large issue history.

**Comment by pixelzoom** [comment] 2016-02-03 16:54
Feedback on https://github.com/phetsims/tasks/issues/465#issuecomment-178958530 

The "priority" group labels look a little off.  There are 5 different groups: "priority1",...,"priority5".  Did you mean for all of these to be "priority"?

**Comment by samreid** [comment] 2016-02-03 16:55
> The "priority" group labels look a little off. There are 5 different groups: "priority1",...,"priority5". Did you mean for all of these to be "priority"?

I am guessing he did that so the alphabetical sorting would match the priority ranking.  Correct me if wrong!

**Comment by ariel-phet** [comment] 2016-02-03 16:57
@pixelzoom yes see https://github.com/phetsims/tasks/issues/465#issuecomment-178962478

**Comment by pixelzoom** [comment] 2016-02-03 17:11
Recommended to use 1 group name, and move the sorting issue to the name. Ie:

priority:1-top
priority:2-high
priority:3-medium
priority:4-low 
priority:5-low

**Comment by jonathanolson** [comment] 2016-02-03 17:12
> Recommended to use 1 group name

Sounds beneficial long-term to me.

**Comment by ariel-phet** [comment] 2016-02-03 17:14
That works for me, will adjust

**Comment by samreid** [comment] 2016-02-03 17:16
Looks great, nice suggestion @pixelzoom

**Comment by mattpen** [comment] 2016-02-04 19:22
Discussed at dev meeting on 2/4/2016.  I'm going to extract the JSON for expression exchange label state and store in phet-info.  I'll also test pushing the new labels to the masses-and-springs repo.

**Comment by mattpen** [comment] 2016-02-05 05:35
I pushed the new labels to masses-and-springs tonight.  Should we automatically replace the github standard-issue labels?  e.g 'bug' becomes 'type:bug'

**Comment by phet-steele** [comment] 2016-02-05 06:19
> Should we automatically replace the github standard-issue labels?

@mattpen no. In fact we will be doing the opposite. It will be a manual task of going through and editing the old labels to match the new one, then deleting the new labels. We want to preserve the old labels so any issue with a preexisting label will not have its label deleted.

**Comment by mattpen** [comment] 2016-02-05 06:29
@phet-steele The reason we're not doing this automatically is because there are too many variations on user-created labels.  I'm just suggesting we update the 6-7 automatically issued labels, not delete and replace.  It would be the same thing you are doing, just in a script.

**Comment by phet-steele** [comment] 2016-02-05 06:34
Oh now that does sound nifty @mattpen! Thoughts @ariel-phet? We should at least test this script, probably in the masses-and-springs repo at this point, with an issue that has a standard label and see if the label is removed after running the script.

**Comment by mattpen** [comment] 2016-02-05 06:36
To clarify, I'm only referring to these labels:
![image](https://cloud.githubusercontent.com/assets/11747676/12839582/135ca4c8-cb98-11e5-8b99-3ff726c709e6.png)

**Comment by phet-steele** [comment] 2016-02-05 06:36
@mattpen I know :smile:

**Comment by mattpen** [comment] 2016-02-05 06:45
The script and standard codes in JSON format are [here](https://github.com/phetsims/phet-info/tree/master/github-labels)

**Comment by ariel-phet** [comment] 2016-02-05 06:55
@mattpen yes, I think it would be safe to replace the standard github labels

**Comment by ariel-phet** [comment] 2016-02-05 06:56
And obviously the "invalid" label can just be deleted

**Comment by mattpen** [comment] 2016-02-05 18:52
[Masses and Springs](https://github.com/phetsims/masses-and-springs/labels) shows the results after running the script I wrote.  

@ariel-phet, Is there another repo you want to test this on?

**Comment by ariel-phet** [comment] 2016-02-05 18:55
@mattpen please try on Friction

If everything works as planned, I would expect the Summer Redeploy label to remain

**Comment by mattpen** [comment] 2016-02-05 19:00
@ariel-phet  I just ran the script for friction, please check at https://github.com/phetsims/friction/labels

**Comment by ariel-phet** [comment] 2016-02-05 19:04
Working as expected. Lets run on all repos. Once complete reassign to me.

**Comment by mattpen** [comment] 2016-02-05 20:43
The new labels have been added to all 119 repos.  I checked a few and it looks like it worked as planned.

**Comment by ariel-phet** [comment] 2016-02-08 01:49
All repos have been double checked and de-duplicated. Closing

**Closed by ariel-phet** 2016-02-08 01:49 UTC
Labels: type:misc
