### ISSUE TITLE
Redeploy LSR

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/tasks#428] opened 2015-11-12 21:34 UTC
As part of the Summer 2015 Redeploy, Least Squares Regression will also need to be redeployed by someone.

**Comment by jessegreenberg** [comment] 2015-11-19 19:55
This is one that I could do since MAL was the only sim I have had to redeploy so far.

**Comment by ariel-phet** [comment] 2015-11-20 05:52
@jessegreenberg sounds good, assigning to you. Lets make getting Trig tour out the priority, and then we can figure out where getting this ready for redeploy lands.

**Comment by ariel-phet** [comment] 2016-01-15 17:22
Closing, dealt with in other issues like https://github.com/phetsims/least-squares-regression/issues/48

**Closed by ariel-phet** 2016-01-15 17:22 UTC
Labels: Summer 2015 redeploy
