### ISSUE TITLE
Update on Office Mix?

### ISSUE THREAD

**Issue by samreid** [phetsims/tasks#450] opened 2015-12-09 16:29 UTC
I wanted to check in on our Office Mix status, are our apps being used there?  How many apps do we have there?  @arouinfar can you comment on this or point me in the right direction?

**Comment by arouinfar** [comment] 2015-12-09 18:09
@samreid I actually do not know our Office Mix status. I had been emailing our liaison with a link to newly published sims, and he was initially quite responsive. However, the last time I heard from him was 11/4/14, and I've reached out to him three times since (latest being 3/25/15). I can do some investigating and see which sims are currently available through the PhET Office Mix App, but I don't know how to check the usage of our sims.

**Comment by arouinfar** [comment] 2015-12-09 18:53
Checking the Office Mix app, we are missing our five newest sims (Molecule Shapes, Molecule Shapes Basics, Least-Squares Regression, Molecules & Light, Hooke's Law). I told the liaison about the first two, but not the others. I will try reaching out to him again.

I also found login credentials for our Microsoft store on Unfuddle, so I will also try logging in and see if the process to add sims to the app is possible/intuitive.

@samreid, Balloons and Static Electricity had an IE specific exception that prevented it from being loaded in an iframe, which meant it couldn't be included in our Office Mix app. Do you know if that's still the case?

**Comment by arouinfar** [comment] 2015-12-09 19:32
I've emailed an update to @ariel-phet and @samreid that details what I found when logging into our Microsoft store. I will contact our Microsoft liaison later this afternoon.

**Comment by samreid** [comment] 2015-12-09 20:22
Balloons and static electricity still cannot be iframed on ID, see https://github.com/phetsims/balloons-and-static-electricity/issues/93

**Comment by ariel-phet** [comment] 2016-01-19 16:30
@arouinfar - status of this issue? Can it be closed?

**Comment by arouinfar** [comment] 2016-01-19 19:58
@ariel-phet I haven't heard back from the liaison, but I will send a follow up email this afternoon. If I don't hear back by the end of the week, I'll close this issue.

**Comment by arouinfar** [comment] 2016-02-04 20:58
No response from the liaison, so closing for now. I'll reopen if there are any updates.

**Comment by oliver-phet** [comment] 2016-08-09 21:22
A user requested the Mix app be updated to include several new sims since the app is now very out of date. Will assign to myself for now.

**Comment by ariel-phet** [comment] 2016-08-26 23:36
This seems like it would be good to fix soon...do we have any sort of admin access?

Does @kathy-phet have a contact at microsoft? Sounds like we need to find a new liaison?

**Comment by arouinfar** [comment] 2016-08-27 00:12
@ariel-phet I'll ping Kurt (our Microsoft liaison) about this and see if I get a response. I'll also shoot you an email about accessing our Office Mix account.

Our Office Mix app predates me. I don't know much about how it works, but from what I understand we cannot add our own content to the app. It must get rerouted through a liaison at Microsoft. Given this, I'm also skeptical that we have much control over how it looks.

**Comment by arouinfar** [comment] 2016-08-31 20:23
Heard back from Kurt, and it looks like there is a way that we can maintain the app in-house. Discussion is continuing over email.

**Comment by arouinfar** [comment] 2016-09-07 19:15
@ariel-phet will be meeting with Kurt to discuss the next steps. Reassigning to him for now.

**Comment by ariel-phet** [comment] 2016-09-07 22:58
Met with Kurt, going to track next steps in special ops since a bit more of an internal discussion

**Closed by ariel-phet** 2016-09-07 22:58 UTC
Labels: priority:3-medium, type:misc
