### ISSUE TITLE
complete S2015R redeploy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tasks#476] opened 2016-01-14 19:09 UTC
At 1/14/2016 dev meeting, we decided that we needed a list of sims that haven't been redeployed with translation support.  Here's the list.  

*Click on a sim name to see that sim's open issues.*

- [x] [Area Builder](https://github.com/phetsims/area-builder/issues) (published on 5/13/2016)
- [x] [Balancing Act](https://github.com/phetsims/balancing-act/issues) (published on 4/7/2016)
- [x] [Balloons and Static Electricity](https://github.com/phetsims/balloons-and-static-electricity/issues) (2/25/16: 1.1.0 published)
- [x] [Build An Atom](https://github.com/phetsims/build-an-atom/issues) (4/22/2016: 1.2.0 published)
- [x] [Color Vision](https://github.com/phetsims/color-vision/issues) (2/16/16: 1.1.0 published)
- [x] [Energy Skate Park: Basics](https://github.com/phetsims/energy-skate-park-basics/issues) (4/11/2016: 1.1.0 published)
- [x] [Forces and Motion: Basics](https://github.com/phetsims/forces-and-motion-basics/issues) (5/6/16: 2.0.0 published)
- [x] [Fraction Matcher](https://github.com/phetsims/fraction-matcher/issues) (@samreid: 1.1.0 published)
- [x] [Gravity Force Lab](https://github.com/phetsims/gravity-force-lab/issues) (3/21/2016 2.0.0 published)
- [x] [John Travoltage](https://github.com/phetsims/john-travoltage/issues) (3/10/16: 1.2.0 published)
- [x] [Least Squares Regression](https://github.com/phetsims/least-squares-regression/issues) (4/19/16: 1.1.0 published )
- [x] [Molecule Shapes](https://github.com/phetsims/molecule-shapes/issues) (1/29/16: 1.1.2 published)
- [x] [Molecule Shapes: Basics](https://github.com/phetsims/molecules-shapes-basics/issues) (1/29/16: 1.1.0 published)
- [x] [Ohm's Law](https://github.com/phetsims/ohms-law/issues) (2/24/16: 1.3.0 published)
- [x] [Resistance In A Wire](https://github.com/phetsims/resistance-in-a-wire/issues) (3/7/2016: 1.2.0 published)
- [x] [Under Pressure](https://github.com/phetsims/under-pressure/issues) (5/17/2016: 1.1.0 published)
- [x] [Wave On A String](https://github.com/phetsims/wave-on-a-string/issues) (3/1/16: 1.1.0 published)

**Comment by pixelzoom** [comment] 2016-01-14 19:10
Mentioning all developers who might be involved in redeploy: @samreid @jbphet @jonathanolson @jessegreenberg

**Comment by pixelzoom** [comment] 2016-01-14 20:08
1/14/2016 status meeting:  

Have testers run string tests on all of the above with the test server, to identify i18n layout issues. @ariel-phet will schedule that work. 

JB would like to prioritize: Ohm's Law, Resistance In A Wire, Build An Atom, Balancing Act, Area Builder

**Comment by pixelzoom** [comment] 2016-01-21 17:55
I edited https://github.com/phetsims/tasks/issues/476#issue-126724851 so that clicking on a sim name takes you to the list of open issues for that sim.

**Comment by pixelzoom** [comment] 2016-02-11 19:26
2/11/16 dev meeting: According to @ariel-phet, testing for i18n problems has been completed.

**Comment by pixelzoom** [comment] 2016-02-11 19:39
2/11/16 dev meeting:

Decided to fix i18n issues, but ignore other issues for now, so that we can get this done.

This does not apply to FAMB, Gravity Force Lab, and Build An Atom, which are all in the process of triaging and fixing issues.

**Comment by pixelzoom** [comment] 2016-02-15 22:11
+1 to wait for 1.0.0 GA, we don't have time for an RC.

**Comment by pixelzoom** [comment] 2016-02-18 19:28
Added developer-meeting label, should make it a weekly practice to check on status of this.

**Comment by samreid** [comment] 2016-02-25 19:31
Ohm's law is the latest published sim, with these shas: https://phet.colorado.edu/sims/html/ohms-law/1.3.0/dependencies.json

But it doesn't have the clipping area fix or the text area artifact fix.

**Comment by samreid** [comment] 2016-02-25 19:32
@jonathanolson said "Wave on a String" has latest scenery fixes and may be a good candidate for next SHAs.

**Comment by jonathanolson** [comment] 2016-03-03 19:34
Use WOAS SHAs (https://github.com/phetsims/wave-on-a-string/blob/1.1/dependencies.json) except for phetcommon, which should use https://github.com/phetsims/phetcommon/commit/380b1fb5f15d097133bfceaf119d3eaf40a3a2d4.

This has NOT been fully tested yet.

**Comment by samreid** [comment] 2016-03-10 01:30
@jessegreenberg and @jonathanolson can you comment on the state of the shas above?  Can I use them for Energy Skate Park: Basics?  Were they used for John Travoltage?

**Comment by jessegreenberg** [comment] 2016-03-10 01:44
The shas mentioned in https://github.com/phetsims/tasks/issues/476#issuecomment-191927692 were used in John Travoltage and passed through the testing task successfully.  Above shas seem good to go, but there may be updates to dependencies that I am not aware of.

**Comment by samreid** [comment] 2016-03-10 03:03
@jonathanolson, what is the state of the SHAs?  I need to know SHAs for building Energy Skate Park: Basics, is the tail of this still good? 

@jonathanolson responded:

> Yes that hasn't changed. Needs the specified (non-HEAD) phetcommon

**Comment by samreid** [comment] 2016-03-10 16:45
I had to grab new shas for Fraction Matcher to pick up sun and scenery-phet fixes.

**Comment by samreid** [comment] 2016-03-10 16:57
Also a note for those who follow in my footsteps, the Wave on a String dependencies.json includes a sha for wave-on-a-string which should be removed for your sim.

**Comment by jbphet** [comment] 2016-03-16 23:12
Balancing Act 1.1.0-rc.1 is being created with the SHA set described in https://github.com/phetsims/tasks/issues/476#issuecomment-191927692, but also adds the vegas and vibe repos.

**Comment by samreid** [comment] 2016-04-05 20:44
New SHAs requested for Energy Skate Park: Basics in https://github.com/phetsims/energy-skate-park-basics/issues/336 and available in http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-rc.2/dependencies.json

**Comment by samreid** [comment] 2016-04-11 21:16
Shas from ESPB 1.1.0-rc.2 were approved for publication.  Future S2015R releases can use those.  Keep in mind that ESPB doesn't use vibe, vegas, shred and possibly others which may need scrutiny during testing.

**Comment by samreid** [comment] 2016-04-11 21:29
Energy Skate Park: 1.1.0 is published on figaro and I have updated the issue description.

**Comment by jessegreenberg** [comment] 2016-04-20 01:04
Least Squares Regression 1.1.0 was published, and the issue description has been updated.  It was published with the SHAs mentioned in https://github.com/phetsims/tasks/issues/476#issuecomment-191927692 since those were the stable SHA's when rc.1 was first published.

**Comment by jbphet** [comment] 2016-04-22 17:37
Build an Atom v1.2.0 was just published and the issue descriptions has been updated.  The SHAs referenced in https://github.com/phetsims/tasks/issues/476#issuecomment-205981346 were used with the addition of recent SHAs for vibe and vegas.

**Comment by jbphet** [comment] 2016-04-25 18:56
A fix was just made to chipper related to the ability to handle per cent symbols in translated strings, see https://github.com/phetsims/rosetta/issues/115.  We should probably have all sims use a version of chipper that is https://github.com/phetsims/chipper/commit/55c02ee94221a6b2cfa022295d60d68cdd37fef3 or later for future deployments.

**Comment by jessegreenberg** [comment] 2016-05-04 21:22
Forces and Motion: Basics 2.0.0-rc.2 is using a new set of SHA's to include the memory leak fixes.

http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.0.0-rc.2/dependencies.json

These SHA's are from master as of 5/2/16 and have not been fully tested yet.

**Comment by jessegreenberg** [comment] 2016-05-06 20:55
Forces and Motion: Basics 2.0.0 was published and SHAs in https://github.com/phetsims/tasks/issues/476#issuecomment-217006786 (which include vibe) passed through RC testing successfully.

**Comment by aadish** [comment] 2016-05-17 19:08
Under Pressure has been published and SHAs are the same as Area Builder except for Scenery which includes fix for pain canvas https://github.com/phetsims/scenery/commit/12bb4bd8fafd173c47691dd717c5b0b545ca2395

**Comment by aadish** [comment] 2016-05-17 19:14
S2015R is complete closing this issue

**Closed by aadish** 2016-05-17 19:14 UTC
Labels: meeting:developer, task:S2015R

**Comment by phet-steele** [comment] 2016-05-17 19:17
@ariel-phet, time for S2016R?
