### ISSUE TITLE
Dev Test Gravity and Orbits 1.0.0-dev.26

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tasks#679] opened 2016-08-19 18:44 UTC
It has been a while since gravity-and-orbits was dev tested, and now would be a good time to find any remaining issues..

**Link to sim:** http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.26/gravity-and-orbits_en.html

As part of this dev test, please also see if you can reproduce https://github.com/phetsims/gravity-and-orbits/issues/208.

Also please check the performance on a few of the slower devices to see where https://github.com/phetsims/gravity-and-orbits/issues/162 is most noticeable.

- [x] iPad2 
- [ ] Chromebook
- [ ] Win Firefox

Assigning to @ariel-phet to prioritize.

**Comment by brroberts1231** [comment] 2016-08-23 17:01
Confirmed phetsims/gravity-and-orbits#208 still occurs on Witten and Lave.

**Comment by ariel-phet** [comment] 2016-08-23 20:58
Moving to medium as #685 needs to take precedence

**Comment by jessegreenberg** [comment] 2016-09-01 15:52
@phet-steele @ariel-phet, we will want to do another dev test after https://github.com/phetsims/gravity-and-orbits/issues/162.  I am not sure how far along this one is, but if you would like to shut this one down and start fresh in the next version, that might prevent having to do extra testing.  Especially since there are  other tasks in line ahead of this one.

**Comment by ariel-phet** [comment] 2016-09-01 16:51
@jessegreenberg - alright closing this task since you have made many new optimizations.

**Closed by ariel-phet** 2016-09-01 16:51 UTC
Labels: priority:3-medium, tasks:QA
